### PR TITLE
Bug Fix Question Default using bad default value

### PR DESCRIPTION
**Pull request by rampmaster**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT

### CODE REVIEW

**Comment by rampmaster** [comment]
@kunicmarko20 yes, i can.

- Test case 1: Execute composer update (Command not execute interactive mode)
- Test case 2: Manual execution command without interactive mode.

Regards

**Comment by kunicmarko20** [comment]
I just tested again and with or without your fix, the first time it is installed and the second time it is asking for interactive mode, and it is the same in both cases. ping @ElectricMaxxx maybe you can confirm this but it is same for me.

**Comment by c0ntax** [comment]
Running `bin/console ckeditor:install --no-interaction`. Then things break. Can confirm that this change fixes the issue as I came here to see if anyone else had fixed it in the same way as me. ;-)

**Comment by kunicmarko20** [comment]
@rampmaster @c0ntax tagged new release https://github.com/FriendsOfSymfony/FOSCKEditorBundle/releases/tag/1.1.0

**Pull request merged**
