### PR TITLE
Symfony 5 support

### PR DESCRIPTION
**Pull request by endroid**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by michaljusiega** [comment]
Please bump the version to use with SF 5.0...

**Comment by mthiebaut** [comment]
Hello,

I'm interessed about this modification, can you merge this request?

**Comment by lsmith77** [comment]
can you rebase on the `2.x` branch?

**Comment by lsmith77** [comment]
please someone test 2.x to confirm if its working in a real world app .. and then I will tag a release

**Comment by nacholibre** [comment]
Just testing this right now, `ckeditor:install` fails, I'm testing using webpack now.

```
user ✗ php bin/console ckeditor:install
----------------------
| CKEditor Installer |
----------------------

 // Downloading CKEditor ZIP archive from "https://github.com/ckeditor/ckeditor-releases/archive/full/latest.zip"

 1744510/1744510 [============================] 100%

 // Extracting CKEditor ZIP archive to "/Users/nacholibre/Development/nachoblog/vendor/friendsofsymfony/ckeditor-bundle/src/Resources/public"


In CKEditorInstaller.php line 256:

  Attempted to load class "ZipArchive" from the global namespace.
  Did you forget a "use" statement?


ckeditor:install [--release [RELEASE]] [--custom-build-id [CUSTOM-BUILD-ID]] [--tag [TAG]] [--clear [CLEAR]] [--exclude [EXCLUDE]] [-nobar|--no-progress-bar] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<path>]```

**Comment by lsmith77** [comment]
hmm that issue would be caused if you don't have ext-zip installed https://www.php.net/manual/en/book.zip.php

but this dependency is listed in the composer.json:
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/2.x/composer.json#L21

**Comment by nacholibre** [comment]
@lsmith77 ops, you are right, I don't have ext-zip, but I ran composer install with different php binary, everything is fine then!

**Comment by lsmith77** [comment]
ah cool .. so you can confirm that master is working fine with Symfony 5 ?

**Comment by nacholibre** [comment]
Yes, it's working.

**Comment by lsmith77** [comment]
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/releases/tag/2.2.0

**Pull request merged**
