### PR TITLE
Return extension in bundle

### PR DESCRIPTION
**Pull request by kunicmarko20**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT

After I started on  #61 I saw some tests are failing:

https://github.com/fsi-open/resource-repository-bundle/pull/67
https://github.com/fsi-open/admin-translatable-bundle/pull/77

Here is a fix, I guess we would miss this if it weren't for @fsi-open

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Do we have to implement the method, or do break some naming conventions?

**Comment by ElectricMaxxx** [comment]
So you said, other bundle do have the same scheme, do they have to implement that method too?

**Comment by kunicmarko20** [comment]
I don't know where to find any other bundle that is like this :sweat_smile:

**Comment by kunicmarko20** [comment]
I would say yes:

https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/DependencyInjection/FOSOAuthServerExtension.php#L106

https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/FOSOAuthServerBundle.php

Same thing.

**Pull request merged**
