### PR TITLE
Indicate trailing slashes in plugin directory config

### PR DESCRIPTION
**Pull request by foucdeg**
Relates to issue https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/128. In Symfony directories are usually specified without trailing slashes, so I feel it might be important to insist on the trailing slash here.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | Issue #128 
| License       | MIT

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Can you please rebase this to 1.x branch as that is the current, we merge later to master

**Comment by foucdeg** [comment]
@kunicmarko20 not sure how to do that, I used Github's online file editor. I'll try another PR from the 1.x version of the file.

**Comment by kunicmarko20** [comment]
Tried changing from github but it just messed things up

**Comment by foucdeg** [comment]
@kunicmarko20 don't worry, I'll open another one from the 1.x version of the file

**Comment by foucdeg** [comment]
See #130

**Pull request closed without merging**
