### PR TITLE
Update namespace

### PR DESCRIPTION
**Pull request by kunicmarko20**
| Q             | A
| ------------- | ---
| Branch?       | "master" for new features / the branch of the current release for fixes
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | #3, #11
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Doing this creates a problem with configuration, eg. we can't use `ivory_ck_editor` I would have to change it. I guess leaving the `Ivory` namespace and doing alias to `FOS` could work, @xabbuh you were talking about that? 

But as this bundle is now part of FOS I think the namespace should be `FOS`, I agree with @stof comment [here](https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/28#issuecomment-384935258)

Or maybe there is a way to have `ivory_ck_editor` config with `FOS` namespace?

**Comment by ElectricMaxxx** [comment]
pls. rebase on master.

**Comment by ElectricMaxxx** [comment]
We shouldn't wait for scrutinizer.

**Comment by kunicmarko20** [comment]
I checked rest of the fos bundles and it should be `fos_ck_editor`

**Comment by kunicmarko20** [comment]
Wait for Travis and this can finally be merged.

**Pull request merged**
