### PR TITLE
Add support for Symfony 6.0

### PR DESCRIPTION
**Pull request by artoroz**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? |/no
| License       | MIT

### CODE REVIEW

**Comment by jmsche** [comment]
Maybe it's time.to drop unsupported versions of PHP?

**Comment by artoroz** [comment]
> Maybe it's time.to drop unsupported versions of PHP?

That would solve the problem of compatibility with phpunit 7
Also added check with php 8.1

**Comment by artoroz** [comment]
Any feedback on this?

**Comment by FluffyDiscord** [comment]
please merge it asap

**Comment by 0x6d6c** [comment]
Also closes #240.

**Comment by paulalbertdev** [comment]
I'd be interested to be able to use FOSCKEditorBundle with Symfony 6 too ;)

**Review by ChristianVermeulen — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Hi @lsmith77, is something needed for this to be merge ? :)

**Comment by lsmith77** [comment]
> Hi @lsmith77, is something needed for this to be merge ? :)

a maintainer :-/

I am not using Symfony for a while now and too busy with my new role as co-founder in a startup.

I fear @ElectricMaxxx also is no longer active on this bundle.

**Comment by lsmith77** [comment]
changes look safe enough .. so merging but we need to someone take over maintenance and do a release.

**Comment by w3sami** [comment]
for anyone else finding themselves in here, because you read the last commit promising sf6 support, but then run into 
Problem 1
    - Root composer.json requires friendsofsymfony/ckeditor-bundle 2.3.0 -> satisfiable by friendsofsymfony/ckeditor-bundle[2.3.0].
    - friendsofsymfony/ckeditor-bundle 2.3.0 requires symfony/asset ^4.4 || ^5.0 -> found symfony/asset[v4.4.0, ..., v4.4.27, v5.0.0, ..., v5.4.0] but these were not loaded, likely because it conflicts with another require.
   
when installing via composer, use composer require friendsofsymfony/ckeditor-bundle:"@dev" to get the latest code with out the release :)

**Comment by ChristianVermeulen** [comment]
> when installing via composer, use composer require friendsofsymfony/ckeditor-bundle:"@dev" to get the latest code with out the release :)

Just be aware you are running a development version of the code which might not have been fully tested yet ;-). I prefer to wait for the next release for production environments.

**Comment by jmsche** [comment]
FYI I've been using artoroz's branch on production for more than a month without any issues.

**Comment by lsmith77** [comment]
the situation is that there is currently not really a proper maintainer. so I would ask people to test this release and provide feedback here. if I see enough people confirming that things work fine, I can do a (last) release.

Note the Bundle might become a UX component in the future:
https://twitter.com/lsmith/status/1479433042229870599?s=21

**Comment by artoroz** [comment]
At this moment i am running at 2.x branch without any problems on production

**Comment by jontjs** [comment]
The 2.x branch is also working for me, with Symfony 6.

**Comment by lsmith77** [comment]
ok cool .. sounds good.

will do a release today or tmorrow

**Comment by lsmith77** [comment]
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/releases/tag/2.4.0

**Pull request merged**
