### PR TITLE
Download behind proxy fix

### PR DESCRIPTION
**Pull request by felipyamorim**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #111 
| License       | MIT

fix stream_context_create proxy option

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Tests are still failing.

**Comment by felipyamorim** [comment]
Works fine in windows, but doesnt work in linux. I will check.

**Comment by felipyamorim** [comment]
The problem is in the proxy address used previously in the test. I changed for another and works.

But, free proxy address runs the risk of stopping working, how can we fix this?

**Comment by kunicmarko20** [comment]
@felipyamorim any chance you can finish this?

**Comment by felipyamorim** [comment]
Yes, i will try, but I need to find one free proxy to test.

**Comment by eiannone** [comment]
I think the problem is that the '`proxy`' option doesn't accept 'http://' in the url, but wants it in the form 'tcp://<proxy_host>:<proxy_port>'.
Please see my PR https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/160

**Pull request closed without merging**
