### PR TITLE
move all files into their folders, adjust psr-4 mapping

### LINKED ISSUE #7: Folder restructure
Move code to `src`.

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
fix #7

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Also, maybe next time fork it instead of adding a branch to the original repo 😅

**Comment by ElectricMaxxx** [comment]
We should have a look into the organisation's CONTRIBUTION.md and Link it here. Depending on that we should handle PRs :-)

**Comment by kunicmarko20** [comment]
When did we enable travis? Should we merge this without travis?

**Comment by ElectricMaxxx** [comment]
I enabled it, cause i didn't want to make blind PRs. The related issue #4 should stay and fix the config.

**Comment by ElectricMaxxx** [comment]
and so the tests telling us, that i made a mistake, will fix it tonight.

**Comment by ElectricMaxxx** [comment]
Now you felt the Advantage having a branch pushed to origen. Colabiration is easier. So thx. I am currently finished sport, and when i am back at home i will hopefully invest some time into our new baby.

**Comment by kunicmarko20** [comment]
You can do that on fork also :smiley:

**Comment by kunicmarko20** [comment]
Tests are failing because of downloading of CKE stuff ...

**Comment by ElectricMaxxx** [comment]
Nothing we should fix here, or is it path related?

**Comment by kunicmarko20** [comment]
I fixed everything and build is passing problem is, it hangs on tests that download stuff from CKE and install it. That is why I suggested https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/31, without groups I can't even run build locally.

**Comment by kunicmarko20** [comment]
https://travis-ci.org/FriendsOfSymfony/FOSCKEditorBundle/jobs/371716250 13 minutes in, just 1 test case was run.

**Comment by kunicmarko20** [comment]
Can we merge this without that 3 tests? This is blocking everything

**Comment by ElectricMaxxx** [comment]
tests are failing in php 5.5, 5.6, which should not be supported that long. so lets merge it.

**Pull request merged**
