### PR TITLE
Drop Composer script

### PR DESCRIPTION
**Pull request by kunicmarko20**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | #20
| License       | MIT

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Should I add a deprecation PR to 1.x?

**Comment by ElectricMaxxx** [comment]
yes, somebody could have used our bash scripts, i really like them as i have  a short hand how to get to a travis result.

**Comment by ElectricMaxxx** [comment]
ah you mean those, yes.

**Comment by ElectricMaxxx** [comment]
please rebase to see changes on master.

**Comment by kunicmarko20** [comment]
What changes? Deprecation PRs are on 1.x while this one is on master (same for the other one). Those files are removed with this PR, no point in rebase.

**Comment by ElectricMaxxx** [comment]
nothin said. was an stupid automatic reaction: rebase. :-)

**Comment by kunicmarko20** [comment]
Oh, then this can get merged? Also #114

**Comment by ElectricMaxxx** [comment]
Oh. Yes

**Pull request merged**
